[build]
target = "riscv32i-unknown-none-elf"

[profile.dev]
opt-level = "s"
lto = false

[profile.release]
debug = true
opt-level = "s"
lto = true

[target.riscv32imc-unknown-none-elf]
rustflags = [
    "-Clink-args=-Tlink.ld -Map=output.map"
]
[target.riscv32i-unknown-none-elf]
rustflags = [
    "-Clink-args=-Tlink.ld -Map=output.map"
]